export const GENRES: { [key: string]: string } = {
  klasyka: 'klasyka',
  literatura_piekna: 'literatura piękna',
  literatura_popularnonaukowa: 'literatura popularnonaukowa',
  poradnik: 'poradnik',
  literatura_psychologiczna: 'literatura psychologiczna',

  // Gatunki epickie (narracyjne)
  powiesc_historyczna: 'powieść historyczna',
  powiesc_przygodowa: 'powieść przygodowa',
  powiesc_kryminalna: 'powieść kryminalna',
  powiesc_fantastyczno_naukowa: 'powieść fantastyczno-naukowa',
  powiesc_fantasy: 'powieść fantasy',
  romans: 'romans',
  horror: 'horror',
  thriller: 'thriller',
  powiesc_gotycka: 'powieść gotycka',
  powiesc_psychologiczna: 'powieść psychologiczna',
  naukowa: 'naukowa',
  // nowela: "nowela",
  opowiadanie: 'opowiadanie',
  bajka: 'bajka',
  // anegdota: "anegdota",
  // epopeja: "epopeja",
  legenda: 'legenda',
  // diariusz: "diariusz",
  reportaz: 'reportaż',
  literatura_faktu: 'literatura faktu',
  biografia: 'biografia',
  autobiografia: 'autobiografia',
  literatura_sensacyjna: 'literatura sensacyjna',
  literatura_mlodziezowa: 'literatura młodzieżowa',

  // Gatunki liryczne (poetyckie)
  // sonet: "sonet",
  // tren: "tren",
  // psalm: "psalm",
  // piesn: "pieśń",
  // fraszka: "fraszka",

  //   hymn: "hymn",
  // oda: "oda",
  // elegia: "elegia",
  // sielanka: "sielanka",
  // ballada: "ballada",
  // ekfraza: "ekfraza",
  // limeryk: "limeryk",
  // pastorałka: "pastorałka",
  // lamentacja: "lamentacja",
  // dytyramb: "dytyramb",

  // Gatunki dramatyczne
  dramat: 'dramat',
  komedia: 'komedia',
  tragedia: 'tragedia',
  tragedikomedia: 'tragedikomedia',
  dramat_romantyczny: 'dramat romantyczny',
  // opera: "opera",
  // musical: "musical",

  // Gatunki publicystyczne i hybrydowe
  esej: 'esej',
  felieton: 'felieton',
  listy: 'listy',
  dzienniki: 'dzienniki',
  pamietnik: 'pamiętnik',
  satyra: 'satyra',
  // traktat: "traktat",

  // Gatunki mieszane i pograniczne
  powiesc_poetycka: 'powieść poetycka',
  poemat_heroikomiczny: 'poemat heroikomiczny',
  komiks: 'komiks',
  manga: 'manga',
};
